model :
    load_proposals: false
    device: cpu
    max_pool: true
    chkpoint: ""
    pixel_mean: [102.9801, 115.9465, 122.7717]
    pixel_std: [1.0, 1.0, 1.0]
input:
    max_size_train: 1333
    min_size_train: 640
    max_size_test: 1333
    min_size_test: 800
    format: BGR
backbone:
    freeze_at: 2
proposal_generator:
    hidden_channels: 512
    min_size: 0.0
anchor_generator:
    sizes: [[64, 128, 256, 512]]
    aspect_ratios: [[0.5, 1.0, 2.0]]
    angles: [[-90.0, 0.0, 90.0]]
    offset: 0
rpn:
    batch_size_per_image : 1
    pre_nms_topk_test: 6000
    post_nms_topk_test: 300
    pre_nms_topk_train : 12000
    post_nms_topk_train : 2000
    in_features : [res4]
    boundary_thresh : -1.0
    iou_thresholds : [0.3, 0.7]
    iou_labels : [0.0, -1.0, 1.0]
    positive_fraction : 0.5
    bbox_reg_weights : [1.0, 1.0, 1.0, 1.0]
    smooth_l1_beta : 0.0
    loss_weight : 1.0
    nms_thresh : 0.7
roi_heads:
    num_classes : 1600
    in_features : [res4]
    iou_thresholds : [0.5]
    iou_labels : [0, 1]
    positive_fraction : 0.25
    score_thresh_test : 0.2
    nms_thresh_test : [0.5, 0.6, 0.7]
    proposal_append_gt : true
roi_box_head:
    bbox_reg_weights : [10.0, 10.0, 5.0, 5.0]
    smooth_l1_beta : 0.0
    pooler_resolution : 14
    pooler_sampling_ratio : 0
    res5halve : False
    attr: true
    num_attrs: 400
    num_fc : 0
    fc_dim : 1024
    num_conv : 0
    conv_dim : 256
    cls_agnostic_bbox_reg : False
resnets:
    depth : 101
    out_features : [res4]
    num_groups : 1
    norm : BN
    width_per_group : 64
    stride_in_1x1 : true
    res5_dilation : 1
    res2_out_channels : 256
    stem_out_channels : 64
solver:
    lr_scheduler_name : warmupmultisteplr
    max_iter : 270000
    base_lr : 0.002
    momentum : 0.9
    weight_decay : 0.0001
    weight_decay_norm : 0.0
    gamma : 0.1
    steps : [210000, 250000]
    warmup_factor : 0.001
    warmup_iters : 1000
    warmup_method : linear
    checkpoint_period : 5000
    ims_per_batch : 1.0
    bias_lr_factor : 1.0
    weight_decay_bias : 0.0
size_divisibility: 0
pad_value: 0.0
min_detections: 36
max_detections: 36
