name: Build dev documentation

on:
  pull_request:

jobs:
  build_and_package:
    runs-on: [self-hosted, doc-builder]
    container:
      image: python:3.8
      options: "-v /home/github_actions:/mnt"
    env:
      PR_NUMBER: ${{ github.event.number }}

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/doc-builder'
          path: doc-builder

      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/transformers'
          path: transformers

      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/notebooks'
          path: notebooks

      - name: Loading cache.
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: v1-test_build_doc
          restore-keys: |
            v1-test_build_doc-${{ hashFiles('setup.py') }}
            v1-test_build_doc

      - name: Setup environment
        run: |
          apt-get -y update && apt-get install -y libsndfile1-dev

          pip install git+https://github.com/huggingface/doc-builder
          cd transformers
          pip install .[dev]
          cd ..

          export TORCH_VERSION=$(python -c "from torch import version; print(version.__version__.split('+')[0])")
          pip install torch-scatter -f https://data.pyg.org/whl/torch-${TORCH_VERSION}+cpu.html

          pip install torchvision
          python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'

          apt install -y tesseract-ocr
          pip install pytesseract
          pip install pytorch-quantization --extra-index-url https://pypi.ngc.nvidia.com
          pip install https://github.com/kpu/kenlm/archive/master.zip

      - name: Setup git
        run: |
          git config --global user.name "Hugging Face Doc Builder"
          git config --global user.email docs@huggingface.co
          
          cd doc-builder
          git pull origin main
          cd ..

          cd notebooks
          git pull origin master
          cd ..
          WRITE=`cat /mnt/WRITE`
          
          rm -rf doc-build-dev
          git clone https://HuggingFaceDocBuilder:$WRITE@github.com/huggingface/doc-build-dev

      - name: Make documentation
        run: |
          doc-builder build transformers transformers/docs/source --build_dir doc-build-dev/$PR_NUMBER --notebook_dir notebooks/transformers_doc --clean

      - name: Push to repositories
        run: |
          cd doc-build-dev
          ls
          git add $PR_NUMBER
          git commit -m "Updated with commit ${{ github.sha }} \n\nSee: https://github.com/huggingface/transformers/commit/${{ github.sha }}"
          git push origin main
