name: Build PR Documentation

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_pr_documentation.yml@use_hf_hub
    with:
      commit_sha: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ github.event.number }}
      package: transformers
      languages: de en es it ko pt
    secrets:
      token: ${{ secrets.HF_DOC_PUSH }}
      comment_bot_token: ${{ secrets.HUGGINGFACE_PUSH }}
