name: Change PR to draft

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  convert_pr_to_draft:
    runs-on: ubuntu-22.04
    name: Convert PR to draft
    steps:
      - name: Convert PR to draft
        shell: bash
        env:
          PR_NUMBER: ${{ github.event.number }}
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          echo $PR_NUMBER
          gh pr ready $PR_NUMBER --repo $REPO --undo
