name: Change PR to draft

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  convert_pr_to_draft:
    runs-on: ubuntu-22.04
    name: Convert PR to draft
    permissions:
      pull-requests: write
      contents: write
    if: github.event.pull_request.draft == false
    steps:
      - name: Convert PR to draft
        shell: bash
        env:
          PR_NUMBER: ${{ github.event.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo $PR_NUMBER
          gh pr ready $PR_NUMBER --repo $REPO --undo
          gh pr comment $PR_NUMBER --repo $REPO --body "Hi ðŸ‘‹, thank you for opening this pull request! The pull request is converted to draft by default. The CI will be paused while the PR is in draft mode. When it is ready for review, please click the \`Ready for review\` button (at the bottom of the PR page). This will assign reviewers and trigger CI."
