name: Delete doc comment trigger

on:
  pull_request:
    types: [ closed ]


jobs:
  delete:
    uses: huggingface/doc-builder/.github/workflows/delete_doc_comment_trigger.yml@main
    with:
      pr_number: ${{ github.event.number }}
