name: Delete dev documentation

on:
  pull_request_target:
    types: [ closed ]


jobs:
  delete:
    uses: huggingface/doc-builder/.github/workflows/delete_doc_comment.yml@main
    with:
      pr_number: ${{ github.event.number }}
      package: transformers
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}