name: Self-hosted runner (scheduled)


on:
  repository_dispatch:
  schedule:
    - cron: "17 2 * * *"
  push:
    branches:
      - check_ds

jobs:
  deepspeed-ci:
    name: DeepSpeed CI
    uses: ./.github/workflows/self-scheduled.yml
    with:
      job: run_all_tests_torch_cuda_extensions_gpu
      slack_report_channel: "#transformers-ci-daily-deepspeed"
    secrets: inherit
