name: Self-hosted runner (AMD scheduled CI caller)

on: []
#  schedule:
#    - cron: "17 2 * * *"

jobs:
  run_scheduled_amd_ci:
    name: Trigger Scheduled AMD CI
    runs-on: ubuntu-22.04
    if: ${{ always() }}
    steps:
      - name: Trigger scheduled AMD CI via workflow_run
        run: echo "Trigger scheduled AMD CI via workflow_run"
