name: Self-hosted runner (nightly-past-ci-caller)

on:
  schedule:
    # 2:17 am on each Sunday and Thursday

    - cron: "17 2 * * 0,4"
  push:
    branches:
      - run_torch_v_2_1

jobs:
  build_nightly_ci_images:
    name: Build Nightly CI Docker Images
    if: (github.event_name == 'schedule') || ((github.event_name == 'push') && startsWith(github.ref_name, 'run_torch_v_2_1'))
    uses: ./.github/workflows/build-nightly-ci-docker-images.yml
    secrets: inherit

  run_nightly_ci:
    name: Nightly CI
    needs: [build_nightly_ci_images]
    uses: ./.github/workflows/self-nightly-scheduled.yml
    secrets: inherit
