name: Self-hosted runner (AMD mi210 scheduled CI caller)

on:
  workflow_run:
    workflows: ["Self-hosted runner (AMD scheduled CI caller)"]
    branches: ["main"]
    types: [completed]
  push:
    branches:
      - run_amd_scheduled_ci_caller*

jobs:
  run_amd_ci:
    name: AMD mi210
    if: (cancelled() != true) && ((github.event_name == 'workflow_run') || ((github.event_name == 'push') && startsWith(github.ref_name, 'run_amd_scheduled_ci_caller')))
    uses: ./.github/workflows/self-scheduled-amd.yml
    with:
      gpu_flavor: mi210
    secrets: inherit
